[build]
  command = "gatsby build"
  functions = "netlify/functions"
  publish = "public"

[[plugins]]
  package = "gatsby-plugin-netlify"

[[plugins]]
  package = "cypress-plugin-netlify"

  [plugins.inputs.postBuild]
    enable = true

  [plugins.inputs]
    enable = true
